### ISSUE TITLE
Compile with an error

### ISSUE THREAD

**Issue by acche** [barretodavid/starknet-erc721-workshop#1]
When I try to compiled ex1 demo, it will prompt an error that I cannot understand where is the bug in, please see below:

`
(cairo_venv) x@ca starknet-erc721 % starknet-compile contracts/ERC721/ERC721.cairo --output compiled/ERC721.json
contracts/ERC721/ERC721.cairo:10:6: Could not find module 'openzeppelin.introspection.ERC165'. Searched in the following paths:
/Users/x/Dev/web3park/cairo/starknet-erc721/openzeppelin/introspection/ERC165.cairo
/Users/x/cairo_venv/lib/python3.8/site-packages/openzeppelin/introspection/ERC165.cairo
from openzeppelin.introspection.ERC165 import ERC165
     ^*******************************^
`

PLEASE HELP.

**Comment by barretodavid** [comment]
Since you published this issue I have updated my code to use the latest OZ package that provides the ERC165 library
