### ISSUE TITLE
Hold-up on ex2

### ISSUE THREAD

**Issue by acche** [barretodavid/starknet-erc721-workshop#2]
Follow the instruction with exercise 2. While I try to verify the contract(**_ex2b_test_declare_animal()_**) after submitting it, it will prompt a msg to reject my request
```
Error in the called contract (0x2d15a378e131b0a9dc323d0eae882bfe8ecc59de0eb206266ca236f823e0a15):
Error message: Token 1 doesn't belong to the evaluator
Error at pc=0:2600:
An ASSERT_EQ instruction failed: 1274519388635697963204543407605438159849675014318520616686163352039693617685 != 183906.....
Cairo traceback (most recent call last):
Unknown location (pc=0:1883)
Unknown location (pc=0:1872)
```
127451... is the Evaluator contract and 183906... is my test account on Argent X. 

Is there anything I make a mistake with?

**Comment by barretodavid** [comment]
Looks like you have to assign that NFT to the Evaluator smart contract before running the test as it's currently assigned to your Argent X account

**Comment by acche** [comment]
> Looks like you have to assign that NFT to the Evaluator smart contract before running the test as it's currently assigned to your Argent X account

So you're saying that function 'declare _animal'?

**Comment by acche** [comment]
solution: https://github.com/surajsharma/starknet-erc721/blob/main/contracts/token/ERC721/ERC721_ex2.cairo
